name: super-test
on: push

jobs:
  linter-actions:
    name: linter code base
    runs-on: ubuntu-latest
    steps:
      - name: Checking code
        uses: actions/checkout@v2
      
      - name: Run super-linter
        uses: github/super-linter@v3
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: $ {{ secrets.GITHUB_TOKEN }}
